name: lerna publish package

on:
    push:
        branches:
            - master

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
                  registry-url: https://npm.pkg.github.com
                  scope: "@ankitbathlazopsmart"
            - run: |
                  git config --global user.name '@ankitbathlazopsmart'
                  git config --global user.email 'ankit.bathla@zopsmart.com'
            - run: npm install
            - run: npx lerna bootstrap
            - run: npx lerna publish patch --yes
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
